language: ruby

services:
  - mysql

rvm:
  - 1.9.3
  - 2.0.0

env:
  - REDMINE_VER=2.1.6
  - REDMINE_VER=2.2.4
  - REDMINE_VER=2.3.3

matrix:
  exclude:
    - rvm: 2.0.0
      env: REDMINE_VER=2.1.6
    - rvm: 2.0.0
      env: REDMINE_VER=2.2.4

before_install:
  - export PLUGIN_NAME=redmine_my_page_queries
  - export DB=mysql
  - export REDMINE_PATH=$HOME/redmine
  - git clone --depth=1 --branch=$REDMINE_VER https://github.com/redmine/redmine.git $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - rake db:create
  - rake db:migrate
  - rake redmine:plugins:migrate

script:
  - rake redmine:plugins:test NAME=$PLUGIN_NAME
